export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const SINGLE_POST_REQUEST = "SINGLE_POST_REQUEST";
export const SINGLE_POST_SUCCESS = "SINGLE_POST_SUCCESS";
export const SINGLE_POST_FAIL = "SINGLE_POST_FAIL";
